=== willnow/TopEdit/src/TopoEdit/BlockEdit/bin/Debug/Data/DeviceData/DeviceBitTypeInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DeviceBitTypeInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DeviceBitTypes">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="DeviceBitType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DeviceBitType">
		<xs:annotation/>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DeviceType" type="DeviceType"/>
				<xs:element name="DeviceSubType" type="xs:string"/>
				<xs:element ref="BitType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BitType">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="Value" type="xs:int"/>
				<xs:element name="Tip" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="DeviceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="无"/>
			<xs:enumeration value="虚拟"/>
			<xs:enumeration value="联锁区"/>
			<xs:enumeration value="车站"/>
			<xs:enumeration value="站台"/>
			<xs:enumeration value="信号机"/>
			<xs:enumeration value="道岔"/>
			<xs:enumeration value="物理区段"/>
			<xs:enumeration value="股道"/>
			<xs:enumeration value="区间逻辑区段"/>
			<xs:enumeration value="车次窗"/>
			<xs:enumeration value="表示灯"/>
			<xs:enumeration value="进路"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== willnow/TopEdit/src/TopoEdit/BlockEdit/bin/Debug/Data/DeviceData/DeviceControlBitTypeInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<DeviceBitTypeInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DeviceBitTypeInfo.xsd">
	<DeviceBitTypes>
		<DeviceBitType>
			<DeviceType>信号机</DeviceType>
			<DeviceSubType>无</DeviceSubType>
			<BitType>
				<Name>封锁</Name>
				<Value>1</Value>
				<Tip>信号机封锁</Tip>
			</BitType>
		</DeviceBitType>
		<DeviceBitType>
			<DeviceType>物理区段</DeviceType>
			<DeviceSubType>无</DeviceSubType>
			<BitType>
				<Name>封锁</Name>
				<Value>5</Value>
				<Tip>物理区段封锁</Tip>
			</BitType>
			<BitType>
				<Name>计轴预复位</Name>
				<Value>6</Value>
				<Tip>计轴预复位</Tip>
			</BitType>
		</DeviceBitType>
	</DeviceBitTypes>
</DeviceBitTypeInfo>

=== willnow/TopEdit/src/TopoEdit/BlockEdit/bin/Debug/Data/DeviceData/DeviceIndicationBitTypeInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<DeviceBitTypeInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DeviceBitTypeInfo.xsd">
	<DeviceBitTypes>
	<DeviceBitType>
			<DeviceType>联锁区</DeviceType>
			<DeviceSubType>联锁区</DeviceSubType>
			<BitType>
				<Name>中心控</Name>
				<Value>1</Value>
				<Tip>中心控</Tip>
			</BitType>
			<BitType>
				<Name>车站控</Name>
				<Value>2</Value>
				<Tip>车站控</Tip>
			</BitType>
			<BitType>
				<Name>联锁控</Name>
				<Value>3</Value>
				<Tip>联锁控</Tip>
			</BitType>
			<BitType>
				<Name>中心故障</Name>
				<Value>4</Value>
				<Tip>中心故障</Tip>
			</BitType>
		</DeviceBitType>
		<DeviceBitType>
			<DeviceType>信号机</DeviceType>
			<DeviceSubType>信号机</DeviceSubType>
			<BitType>
				<Name>封锁</Name>
				<Value>1</Value>
				<Tip>信号机封锁</Tip>
			</BitType>
			<BitType>
				<Name>红灯</Name>
				<Value>2</Value>
				<Tip>红灯</Tip>
			</BitType>
			<BitType>
				<Name>绿灯</Name>
				<Value>3</Value>
				<Tip>绿灯</Tip>
			</BitType>
			<BitType>
				<Name>黄灯</Name>
				<Value>4</Value>
				<Tip>黄灯</Tip>
			</BitType>
		</DeviceBitType>
		<DeviceBitType>
			<DeviceType>物理区段</DeviceType>
			<DeviceSubType>物理区段</DeviceSubType>
			<BitType>
				<Name>封锁</Name>
				<Value>5</Value>
				<Tip>物理区段封锁</Tip>
			</BitType>
			<BitType>
				<Name>物理占用</Name>
				<Value>6</Value>
				<Tip>物理占用</Tip>
			</BitType>
		</DeviceBitType>
		<DeviceBitType>
			<DeviceType>股道</DeviceType>
			<DeviceSubType>股道</DeviceSubType>
			<BitType>
				<Name>逻辑占用</Name>
				<Value>7</Value>
				<Tip>逻辑占用</Tip>
			</BitType>
		</DeviceBitType>
	</DeviceBitTypes>
</DeviceBitTypeInfo>
