=== willnow/TopEdit/src/TopoEdit/BlockEdit/bin/Debug/Data/DeviceData/DeviceSubTypeInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DeviceSubTypeInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DeviceSubTypes">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="DeviceSubType" minOccurs="12" maxOccurs="12"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DeviceSubType">
		<xs:annotation/>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DeviceType" type="DeviceType"/>
				<xs:element name="SubType" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="DeviceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="无"/>
			<xs:enumeration value="虚拟"/>
			<xs:enumeration value="联锁区"/>
			<xs:enumeration value="车站"/>
			<xs:enumeration value="站台"/>
			<xs:enumeration value="信号机"/>
			<xs:enumeration value="道岔"/>
			<xs:enumeration value="物理区段"/>
			<xs:enumeration value="股道"/>
			<xs:enumeration value="区间逻辑区段"/>
			<xs:enumeration value="车次窗"/>
			<xs:enumeration value="表示灯"/>
			<xs:enumeration value="进路"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== willnow/TopEdit/src/TopoEdit/BlockEdit/bin/Debug/Data/DeviceData/DeviceSubTypeInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<DeviceSubTypeInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DeviceSubTypeInfo.xsd">
	<DeviceSubTypes>
		<DeviceSubType>
			<DeviceType>信号机</DeviceType>
			<SubType>信号机</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>物理区段</DeviceType>
			<SubType>物理区段</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>站台</DeviceType>
			<SubType>站台</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>联锁区</DeviceType>
			<SubType>联锁区</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>股道</DeviceType>
			<SubType>股道</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>区间逻辑区段</DeviceType>
			<SubType>区间逻辑区段</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>虚拟</DeviceType>
			<SubType>虚拟</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>表示灯</DeviceType>
			<SubType>表示灯</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>车次窗</DeviceType>
			<SubType>车次窗</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>车站</DeviceType>
			<SubType>车站</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>道岔</DeviceType>
			<SubType>道岔</SubType>
		</DeviceSubType>
		<DeviceSubType>
			<DeviceType>进路</DeviceType>
			<SubType>进路</SubType>
		</DeviceSubType>
	</DeviceSubTypes>
</DeviceSubTypeInfo>
