=== willnow/TopEdit/src/TopoEdit/BlockEdit/bin/Debug/Data/DeviceData/SubwayDeviceInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Tde">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="StationGroups">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="StationGroup" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StationGroup">
		<xs:annotation/>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="Id" type="xs:int"/>
				<xs:element ref="Device" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="BitValueInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Type" type="xs:int"/>
				<xs:element name="Value" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="DeviceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="无"/>
			<xs:enumeration value="虚拟"/>
			<xs:enumeration value="联锁区"/>
			<xs:enumeration value="车站"/>
			<xs:enumeration value="站台"/>
			<xs:enumeration value="信号机"/>
			<xs:enumeration value="道岔"/>
			<xs:enumeration value="物理区段"/>
			<xs:enumeration value="股道"/>
			<xs:enumeration value="区间逻辑区段"/>
			<xs:enumeration value="车次窗"/>
			<xs:enumeration value="表示灯"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="DeviceInfo">
		<xs:sequence>
			<xs:element name="StationGroupNo" type="xs:int"/>
			<xs:element name="DeviceType" type="DeviceType"/>
			<xs:element name="DeviceHandle" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Device">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Guid" type="xs:string"/>
				<xs:element name="DeviceType" type="DeviceType"/>
				<xs:element name="DeviceSubType" type="xs:string"/>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="StationNo" type="xs:int"/>
				<xs:element name="BitInfo" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Indication">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="BitValueInfo" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Control">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="BitValueInfo" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="LinkIcons">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Icon" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:choice>
					<xs:element ref="PhysicTrack"/>
					<xs:element ref="Platform"/>
					<xs:element ref="Station"/>
					<xs:element ref="Window"/>
					<xs:element ref="Alarm"/>
					<xs:element ref="LinkDevice"/>
					<xs:element ref="Head"/>
					<xs:element ref="Null"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="Index" type="xs:int"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="DirType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Up"/>
			<xs:enumeration value="Down"/>
			<xs:enumeration value="Dual"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SwitchDirType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="左上"/>
			<xs:enumeration value="左下"/>
			<xs:enumeration value="右上"/>
			<xs:enumeration value="右下"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="LinkDevice">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Dir" type="DirType"/>
				<xs:choice>
					<xs:element ref="DeviceWithWindow"/>
					<xs:element ref="Signal"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DeviceWithWindow">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Window" type="xs:string" maxOccurs="unbounded"/>
				<xs:element name="PhysicTrack" type="xs:string"/>
				<xs:choice>
					<xs:element ref="LogicTrack"/>
					<xs:element ref="Switch"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LogicTrack">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="UpLinkDevice" type="xs:string"/>
				<xs:element name="DownLinkDevice" type="xs:string"/>
				<xs:element name="Length" type="xs:int"/>
				<xs:element name="KmStart" type="xs:int"/>
				<xs:choice>
					<xs:element ref="LogicTrackInStation"/>
					<xs:element ref="LogicTrackOutStation"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LogicTrackInStation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Platform" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LogicTrackOutStation">
		<xs:complexType>
			<xs:sequence/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Switch">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NormalLinkDevice" type="xs:string"/>
				<xs:element name="ReverseLinkDevice" type="xs:string"/>
				<xs:element name="MainLinkDevice" type="xs:string"/>
				<xs:element name="SwitchDir" type="SwitchDirType"/>
				<xs:element name="MainKM" type="xs:int"/>
				<xs:element name="NormalKM" type="xs:int"/>
				<xs:element name="ReverseKM" type="xs:int"/>
				<xs:element name="CenterKM" type="xs:int"/>
				<xs:element name="MainCbtcBlockId" type="xs:int"/>
				<xs:element name="NormalCbtcBlockId" type="xs:int"/>
				<xs:element name="ReverseCbtcBlockId" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Signal">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="UpLinkDevice" type="xs:string"/>
				<xs:element name="DownLinkDevice" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Window">
		<xs:complexType>
			<xs:sequence/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Alarm">
		<xs:complexType>
			<xs:sequence/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Platform">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PlatformId" type="xs:int"/>
				<xs:element name="DestNo" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Station">
		<xs:complexType>
			<xs:sequence/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PhysicTrack">
		<xs:complexType>
			<xs:sequence/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Head">
		<xs:complexType>
			<xs:sequence/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Null">
		<xs:complexType>
			<xs:sequence/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== willnow/TopEdit/src/TopoEdit/BlockEdit/bin/Debug/Data/DeviceData - 副本/SubwayDeviceInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<Tde xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SubwayDeviceInfo.xsd">
	<StationGroups>
		<StationGroup>
			<Name>光达</Name>
			<Id>1</Id>
			<Device>
				<Name>T2954-1</Name>
				<StationNo>1</StationNo>
				<GeneralInfo>
					<StationGroupNo>1</StationGroupNo>
					<DeviceType>股道</DeviceType>
					<DeviceHandle>1</DeviceHandle>
				</GeneralInfo>
				<BitInfo>
					<Indication>
                    </Indication>
					<Control>
						<BitValueInfo>
							<Type>1</Type>
							<Value>1</Value>
						</BitValueInfo>
					</Control>
				</BitInfo>
				<LinkIcons>
					<Icon>T2954-1</Icon>
				</LinkIcons>
				<LinkDevice>
					<Dir>Up</Dir>
					<DeviceWithWindow>
						<Window>
							<StationGroupNo>1</StationGroupNo>
							<DeviceType>车次窗</DeviceType>
							<DeviceHandle>1</DeviceHandle>
						</Window>
						<PhysicTrackName>T2954</PhysicTrackName>
						<LogicTrack>
							<UpLinkDevice>
								<StationGroupNo>0</StationGroupNo>
								<DeviceType>无</DeviceType>
								<DeviceHandle>0</DeviceHandle>
							</UpLinkDevice>
							<DownLinkDevice>
								<StationGroupNo>0</StationGroupNo>
								<DeviceType>无</DeviceType>
								<DeviceHandle>0</DeviceHandle>
							</DownLinkDevice>
							<Length>1000</Length>
							<KmStart>0</KmStart>
							<KmEnd>1100</KmEnd>
							<LogicTrackInStation>
								<Platform>
									<StationGroupNo>0</StationGroupNo>
									<DeviceType>无</DeviceType>
									<DeviceHandle>0</DeviceHandle>
								</Platform>
							</LogicTrackInStation>
						</LogicTrack>
					</DeviceWithWindow>
				</LinkDevice>
			</Device>
		</StationGroup>
	</StationGroups>
</Tde>

=== willnow/TopEdit/src/TopoEdit/BlockEdit/bin/Debug/Data/DeviceData/SubwayDeviceInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<Tde xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SubwayDeviceInfo.xsd">
  <StationGroups>
    <StationGroup>
      <Name>光达站</Name>
      <Id>1</Id>
      <Device>
        <Guid>d3975ae8-ebb2-4f55-b8f4-57f9e3719cbc</Guid>
        <DeviceType>联锁区</DeviceType>
        <DeviceSubType>联锁区</DeviceSubType>
        <Name>光达站</Name>
        <StationNo>1</StationNo>
        <BitInfo>
          <Indication>
            <BitValueInfo>
              <Type>1</Type>
              <Value>1</Value>
            </BitValueInfo>
            <BitValueInfo>
              <Type>2</Type>
              <Value>2</Value>
            </BitValueInfo>
            <BitValueInfo>
              <Type>3</Type>
              <Value>3</Value>
            </BitValueInfo>
            <BitValueInfo>
              <Type>4</Type>
              <Value>4</Value>
            </BitValueInfo>
          </Indication>
          <Control>
          </Control>
        </BitInfo>
        <LinkIcons>
          <Icon>GenerAlarm1</Icon>
        </LinkIcons>
        <Head />
      </Device>
      <Device>
        <Guid>bb376da1-563d-45ca-989b-6a4fc05886b3</Guid>
        <DeviceType>道岔</DeviceType>
        <DeviceSubType>道岔</DeviceSubType>
        <Name>Switch_Right_Down_45</Name>
        <StationNo>1</StationNo>
        <BitInfo>
          <Indication>
          </Indication>
          <Control>
          </Control>
        </BitInfo>
        <LinkIcons>
          <Icon>Switch_Right_Down_451</Icon>
          <Icon>Switch_Right_Down_45</Icon>
        </LinkIcons>
        <LinkDevice>
          <Dir>Up</Dir>
          <DeviceWithWindow>
            <Window />
            <PhysicTrack>
            </PhysicTrack>
            <Switch>
              <NormalLinkDevice />
              <ReverseLinkDevice />
              <MainLinkDevice />
              <SwitchDir>右上</SwitchDir>
              <MainKM>0</MainKM>
              <NormalKM>0</NormalKM>
              <ReverseKM>0</ReverseKM>
              <CenterKM>0</CenterKM>
              <MainCbtcBlockId>0</MainCbtcBlockId>
              <NormalCbtcBlockId>0</NormalCbtcBlockId>
              <ReverseCbtcBlockId>0</ReverseCbtcBlockId>
            </Switch>
          </DeviceWithWindow>
        </LinkDevice>
      </Device>
      <Device>
        <Guid>7bea7b2a-f25c-43bf-bc2c-ac875168b37b</Guid>
        <DeviceType>股道</DeviceType>
        <DeviceSubType>股道</DeviceSubType>
        <Name>Track2</Name>
        <StationNo>1</StationNo>
        <BitInfo>
          <Indication>
            <BitValueInfo>
              <Type>7</Type>
              <Value>5</Value>
            </BitValueInfo>
          </Indication>
          <Control>
          </Control>
        </BitInfo>
        <LinkIcons>
          <Icon>Track1</Icon>
        </LinkIcons>
        <LinkDevice>
          <Dir>Up</Dir>
          <DeviceWithWindow>
            <Window />
            <PhysicTrack>
            </PhysicTrack>
            <LogicTrack>
              <UpLinkDevice />
              <DownLinkDevice />
              <Length>0</Length>
              <KmStart>0</KmStart>
              <LogicTrackInStation>
                <Platform />
              </LogicTrackInStation>
            </LogicTrack>
          </DeviceWithWindow>
        </LinkDevice>
      </Device>
      <Device>
        <Guid>073588f6-e6d2-486e-9712-f19e44fd58d8</Guid>
        <DeviceType>站台</DeviceType>
        <DeviceSubType>站台</DeviceSubType>
        <Name>111111</Name>
        <StationNo>1</StationNo>
        <BitInfo>
          <Indication>
          </Indication>
          <Control>
          </Control>
        </BitInfo>
        <LinkIcons>
          <Icon>111111</Icon>
        </LinkIcons>
        <Platform>
          <PlatformId>3</PlatformId>
          <DestNo>dsdfsdf</DestNo>
        </Platform>
      </Device>
      <Device>
        <Guid>93a7ff61-ee77-4e2a-b1be-92fa060b7056</Guid>
        <DeviceType>信号机</DeviceType>
        <DeviceSubType>无</DeviceSubType>
        <Name>Signal_Down1</Name>
        <StationNo>1</StationNo>
        <BitInfo>
          <Indication>
          </Indication>
          <Control>
          </Control>
        </BitInfo>
        <LinkIcons>
          <Icon>Signal_Down1</Icon>
        </LinkIcons>
        <LinkDevice>
          <Dir>Up</Dir>
          <Signal>
            <UpLinkDevice />
            <DownLinkDevice />
          </Signal>
        </LinkDevice>
      </Device>
    </StationGroup>
    <StationGroup>
      <Name>长沙火车南站</Name>
      <Id>0</Id>
    </StationGroup>
    <StationGroup>
      <Name>万家丽广场</Name>
      <Id>0</Id>
    </StationGroup>
    <StationGroup>
      <Name>长沙大道站</Name>
      <Id>0</Id>
    </StationGroup>
  </StationGroups>
</Tde>
